# This workflow will build all flavors of your React Native for Windows native
#  module project every time changes are pushed to main. This checks that
# every change builds on Windows.

name: Native Module CI

on:
  push:
    branches:
      - main

jobs:
  # This job builds both Debug and Release versions of the native module, for
  # x86, x64, ARM and ARM64 architectures. It doesn't deploy, because deploying
  # is for apps only.
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [x86, x64, ARM, ARM64]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Yarn install
        run: yarn install

      - name: Run react-native run-windows
        run: npx react-native run-windows --logging --no-packager --no-deploy --no-launch --arch ${{ matrix.architecture }} ${{ matrix.configuration == 'Release' && '--release' || '' }}
