# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a295fd249f88f172172b63e4e81ee2aed2c401731331ad90b6a8ce6d0e8bdfce1573f4e7517b0a488f60d56e148474ccd63b0beb936cc5ed891f4d9a928b6eb9

test:
  secret_key_base: 15d5a6a1121371e813d89d362b28d2d80e93ed76f7f7f5da333266bad0189503878c97c06539f61094f93fc390548d92c800f0f3d1d2e4fd7a848c05889c9e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
