# references:
# https://medium.com/@yitaek/practical-monitoring-with-prometheus-grafana-part-ii-5020be20ebf6
groups:
- name: blackbox_alerts.yml
  rules:
  - alert: blackbox_exporter_down
    expr: up{job="blackbox-exporter"} == 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Blackbox exporter is down"
      description: "Blackbox exporter is down or not being scraped correctly"
      
  - alert: probe_failing
    expr: probe_success{job="blackbox-exporter"} == 0
    for: 5m
    labels:
      severity: page
      priority: P1
    annotations:
      summary: "Endpoints are down"
      description: "Endpoint {{ $labels.instance }} is unresponsive for more than 5m"
