# This is a basic workflow to help you get started with Actions

name: Update blog posts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    repository_dispatch:
        types: [blogpost]
    push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run blog.py with latest Python version
      run: python blog.py
      env: 
        TOKEN: ${{ secrets.token }}
    - uses: mikeal/publish-to-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you