version: "3"
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: flask-server
    environment: 
      - FLASK_ENV=development
    ports: 
      - "5000:5000"
  redis: 
    image: redis:4.0.11-alpine