language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TUjXaNrrgIj0pGoQZhqWbxPh8FSc6YtSnF4Vici01xHX8gaGKY97Y/MLKCllloWock6VeQacZtAzEQnJG8IDAADgkCVsRwgaqZurEVhs5nvAAEl8S+fpuJE85LWZxey41/hlTcHFTdZsOof5U4bV8mXraunvYeSJ/7tTwhhjym8=
  file:
    - "linked-list.js"
    - "linked-list.min.js"
  on:
    tags: true
