# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da0593d0bf342e457f6790483442da9e4aaeb1ac46c953756ebff1acf71a8b039b7ef642bf6358e9b9986e4a1113bd69e60f45b9a057e4933e9ee0c4167789a4

test:
  secret_key_base: cadcfa5ac4a100f7b7abce4fd9911843db5ae624c5f3391a47a20ff51fe773e6c6d0b220d1e432eaa1fbb4f4836756463b752894af465eb1dd1713dba688151e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
