version: '3.1'

services: # list of containers
  webapp: # name of service
    build: 
        context: .
        dockerfile: whateverthenameis.Dockerfile
    image: whateverImage:whatevertag # name and tag the built image by this name
    image: # the image this service will use
    ports: 
        - '80:80'
    command: # Optional, will replace the default CMD specified by the image
    environment: # Optional, same as -e in docker container run
    volumes: # Optional, same as -v in docker container run
  psql: # servicename2

volumes: # Optional, same as docker volume create

networks: # Optional, same as docker network create


# for rails:
# docker-compose run web rails new --database=postgresql -J --skip-coffee 
# docker-compose run web rails db:migrate
# docker-compose run web rails db:seed 

