# This workflow will build just one configuration (Debug x86) of your React
# Native for Windows app project on every pull request targeting main. This
# is meant to be a quick sanity check that a pull request doesn't break the
# build, without spending the resources to build every flavor / configuration.

name: App PR

on:
  pull_request:
    branches:
      - main

jobs:
  # This job builds the Debug x86 version of the app.
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Gather environment info
        run: npx envinfo

      - name: Yarn install
        run: yarn install

      - name: Build x86 Debug
        run: npx react-native run-windows --no-launch --no-packager --logging
