name: RNW Website CI

on:
  schedule:
    - cron: '0 15 * * 2' # Tuesday 3PM UTC (8AM PST)
  push:
    branches:
      - main
    paths:
      - '.github/workflows/website-ci.yml'
      - '.github/workflows/website-pr.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  website_ci:
    name: Website CI
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Check for Broken Links (Docs)
      run: npx unbroken --parse-ids
      working-directory: ./docs
    - name: Check for Broken Links (Website)
      if: success() || failure()
      run: npx unbroken --parse-ids
      working-directory: ./website
    - name: Yarn Install (Website)
      if: success() || failure()
      run: yarn install --frozen-lockfile
      working-directory: ./website
    - name: Yarn Build (Website)
      run: yarn build
      working-directory: ./website
