language: node_js
node_js:
  - 10
  - 12
  - 14
os:
  - linux
  - osx

script:
  - "npm run hint"
  - "npm run test"
  - "npm run cover"

after_script: "cat ./coverage/lcov.info | coveralls"

matrix:
  allow_failures:
    - os: osx
